server {
    listen 9300;

    location /pm2/ {
        rewrite ^/pm2(/.*)?$ $1 break;
        proxy_pass http://host.docker.internal:9209;
        add_header Content-Type 'text/plain; version=0.0.4; charset=utf-8' always;
    }
}
